# Stage 1: Build stage
FROM eclipse-temurin:21-jdk AS build
WORKDIR /app

# Copy configuration files
COPY gradlew .
COPY gradle gradle
COPY build.gradle.kts .
COPY settings.gradle.kts .
COPY gradle.properties .

# Copy source code for all modules
COPY client client
COPY core core
COPY server server

# Build the Fat JAR (Shadow JAR)
RUN chmod +x gradlew
RUN ./gradlew :server:buildFatJar --no-daemon

# Stage 2: Runtime stage
FROM eclipse-temurin:21-jre
WORKDIR /app

# Copy the built JAR from the build stage
# The asterisk ensures we pick up the Fat JAR generated by Ktor
COPY --from=build /app/server/build/libs/*-all.jar app.jar

# Railway and other cloud providers use the PORT environment variable
ENV PORT=8080
EXPOSE 8080

# Run the application
# We use the JAR's default entry point defined in build.gradle.kts
CMD ["java", "-jar", "app.jar"]
